apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: otel-gateway-env
    behavior: merge
    literals:
      - GATEWAY_COLLECTOR_CONFIG=otel-collector-gateway-low-noise.yaml
