apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otel-gateway
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: otel-gateway
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
  volumeClaimTemplates:
    - metadata:
        name: otel-gateway-data
      spec:
        storageClassName: REPLACE_WITH_HA_STORAGE_CLASS
        resources:
          requests:
            storage: 50Gi
