apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-gateway
  labels:
    app.kubernetes.io/name: otel-gateway
    app.kubernetes.io/part-of: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-gateway
subjects:
  - kind: ServiceAccount
    name: otel-gateway
    namespace: observability

