apiVersion: v1
kind: Service
metadata:
  name: otel-gateway-headless
  labels:
    app.kubernetes.io/name: otel-gateway
    app.kubernetes.io/part-of: observability
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: otel-gateway
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: health
      port: 13133
      targetPort: health

