apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-gateway
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-gateway
    app.kubernetes.io/part-of: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-gateway
      observability.my-org/service-role: admin
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 10s
      path: /metrics
